/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 2020_polestar.glb 
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2020-polestar-2-24f78b3dc6e84fe0b0b2afdb43d547ea
Title: 2020 Polestar 2
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";
import { Color } from "three";
import { goodColors } from "../../assets/data";

export function Polestar_Car(props) {
  const { nodes, materials } = useGLTF('/2020_polestar.glb');

  // Dynamic Color Change Effect

  const [targetColorIndex, setTargetColorIndex] = useState(0);

  const bodyMaterial = materials.MAT_Carpaint_Black1;

  const currentColor = useRef(new Color(goodColors[0]));
  const targetColor = useRef(new Color(goodColors[0]));

  bodyMaterial.roughness = 0.1;

  useEffect(() => {
    if (bodyMaterial) {
      targetColor.current.set(goodColors[targetColorIndex]);
    }
  }, [targetColorIndex, goodColors, bodyMaterial]);

  // useFrame for smooth color transition
  useFrame((state, delta) => {
    if (bodyMaterial) {
      currentColor.current.lerp(targetColor.current, 0.7 * delta);
      bodyMaterial.color.copy(currentColor.current);
    }
  });

  const changeColorOnClick = () => {
    setTargetColorIndex((prevIndex) => (prevIndex + 1) % goodColors.length);
  };

  return (
    <group onClick={changeColorOnClick} {...props} dispose={null} scale={15} position={[0, 0, 0]}>
      <group scale={0.01}>
        <group position={[0, 0, -0.004]} rotation={[0, Math.PI / 2, 0]} scale={0.984}>
          <mesh geometry={nodes.Yu7carTyre_02_carTyre_02_aiAmbientOcclusion4_tyre_3_0.geometry} material={materials.tyre_3} position={[-1.432, 0.407, 0.792]} />
          <mesh geometry={nodes.carTyre_02_carTyre_02_aiAmbientOcclusion4_tyre_3_0.geometry} material={materials.tyre_3} position={[1.337, 0.407, 0.804]} />
          <mesh geometry={nodes.carTyre_02_carTyre_02_aiAmbientOcclusion5_tyre_3_0.geometry} material={materials.tyre_3} position={[1.337, 0.407, -0.804]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.carTyre_02_carTyre_02_aiAmbientOcclusion6_tyre_3_0.geometry} material={materials.tyre_3} position={[-1.432, 0.407, -0.792]} rotation={[-Math.PI, 0, -Math.PI]} />
        </group>
        <group position={[0, 0.2, 0]}>
          <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_005__MAT_Glass1_0.geometry} material={materials.MAT_Glass1} />
          <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_005_red_glass_0.geometry} material={materials.red_glass} />
          <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_005_glass_light_0.geometry} material={materials.glass_light} />
          <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_005_D_glass_0.geometry} material={materials.D_glass} />
        </group>
        <mesh geometry={nodes._SM_Base_0000_001_SM_Base_0000_MAT_Polestar_2_Base__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_00__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_00__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_01__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_01__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_02__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_02__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_03__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Base_0000_001_SM_Base_0000_MAT_Polestar_2_Base1__MAT_Glass1_0.geometry} material={materials.MAT_Glass1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_03__MAT_Glass1_0.geometry} material={materials.MAT_Glass1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Base_0000_001_SM_Base_0000_MAT_Polestar_2_Base2__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_04__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_04__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_05__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_05__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_06__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Base_0000_001_SM_Base_0000_MAT_Polestar_2_Base3__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_07__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_06__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_08__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Base_0000_001_SM_Base_0000_MAT_Polestar_2_Base4__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_09__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_07__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_08__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_11__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_09__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_12__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_10__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_13__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_11__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_14__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_12__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_15__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_13__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_16__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_14__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_17__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_15__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_18__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_16__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_19__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_17__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_20__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Base_0000_001_SM_Base_0000_MAT_Polestar_2_Base5__MAT_Alpha_02_0.geometry} material={materials.MAT_Alpha_02} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_21__MAT_Alpha_02_0.geometry} material={materials.MAT_Alpha_02} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Brake_FL_0000_001_SM_Brake_FL_0000_MAT_Tire_Brake__MAT_Tire_Brake1_0.geometry} material={materials.MAT_Tire_Brake1} position={[-0.777, 0.401, 1.404]} scale={1.112} />
        <mesh geometry={nodes._SM_Brake_FR_0000_001_SM_Brake_FR_0000_MAT_Tire_Brake_001__MAT_Tire_Brake1_0.geometry} material={materials.MAT_Tire_Brake1} position={[0.792, 0.401, 1.404]} scale={1.112} />
        <mesh geometry={nodes._SM_Brake_RL_0000_001_SM_Brake_RL_0000_MAT_Tire_Brake_002__MAT_Tire_Brake1_0.geometry} material={materials.MAT_Tire_Brake1} position={[0.789, 0.401, -1.319]} scale={1.112} />
        <mesh geometry={nodes._SM_Brake_RR_0000_001_SM_Brake_RR_0000_MAT_Tire_Brake_003__MAT_Tire_Brake1_0.geometry} material={materials.MAT_Tire_Brake1} position={[-0.789, 0.401, -1.319]} scale={1.112} />
        <mesh geometry={nodes._SM_Disk_L_0000_001_SM_Disk_L_0000_MAT_Tire_Disk__MAT_Tire_Disk1_0.geometry} material={materials.MAT_Tire_Disk1} position={[0.792, 0.401, 1.404]} scale={1.112} />
        <mesh geometry={nodes._SM_Disk_R_0000_001_SM_Disk_R_0000_MAT_Tire_Disk_001__MAT_Tire_Disk1_0.geometry} material={materials.MAT_Tire_Disk1} position={[-0.777, 0.401, 1.404]} scale={1.112} />
        <mesh geometry={nodes._SM_FrontKit_0000_001_SM_FrontKit_0000_MAT_Polestar_2_Base_001__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_FrontKit_0000_001_SM_FrontKit_0000_MAT_Polestar_2_Base_002_glass_light_0.geometry} material={materials.glass_light} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_FrontKit_0000_001_SM_FrontKit_0000_MAT_Polestar_2_Base_003__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_FrontKit_0000_001_SM_FrontKit_0000_MAT_Polestar_2_Base_004__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_FrontKit_0000_001_SM_FrontKit_0000_MAT_Polestar_2_Base_005__MAT_Details_Chassis_0001_002_0.geometry} material={materials.MAT_Details_Chassis_0001_002} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Hood_0000_001_SM_Hood_0000_MAT_Polestar_2_Base_002__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Hood_0000_001_SM_Hood_0000_MAT_Polestar_2_Base_003__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Hub_L_0000_001_SM_Hub_L_0000_MAT_Tire_Hub__MAT_Tire_Hub1_0.geometry} material={materials.MAT_Tire_Hub1} position={[0.777, 0.401, 1.404]} scale={[0.675, 1.112, 1.112]} />
        <mesh geometry={nodes._SM_Hub_R_0000_001_SM_Hub_R_0000_MAT_Tire_Hub_001__MAT_Tire_Hub1_0.geometry} material={materials.MAT_Tire_Hub1} position={[-0.777, 0.401, 1.404]} scale={[0.675, 1.112, 1.112]} />
        <mesh geometry={nodes._SM_Interior_0000_001_SM_Interior_0000_MAT_Polestar_2_Base_003__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_22__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_18__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_00__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_23__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_19__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_01__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_24__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_20__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_02__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_25__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_21__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_03__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_26__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_22__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_27__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_23__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_04__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Interior_0000_001_SM_Interior_0000_MAT_Polestar_2_Base_004__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_28__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_24__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_05__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_29__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_25__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_06__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_00__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_07__MAT_Details_INT1_0.geometry} material={materials.MAT_Details_INT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Interior_0000_001_SM_Interior_0000_MAT_Polestar_2_Base_005__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_30__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_26__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Interior_0000_001_SM_Interior_0000_MAT_Polestar_2_Base_006__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_01__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_08__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_31__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_09__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_32__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_10__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_27__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_11__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_28__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_12__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_33__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_29__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_02__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_30__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_03__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_13__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_04__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_14__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_34__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_15__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_35__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_16__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_31__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_17__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_36__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_32__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_18__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_05__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_19__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_37__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_33__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_20__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_06__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_21__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_38__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_34__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_22__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_07__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_23__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_39__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_35__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_24__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_08__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_25__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_40__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_36__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_26__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_09__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_27__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_41__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_37__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_28__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_42__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_10__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_29__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_38__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_30__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_43__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_31__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_44__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_39__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_45__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_40__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_11__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_46__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_41__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_32__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_47__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_42__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_33__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_48__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_34__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_12__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_35__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_R_49__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_36__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_SteeringWheel_13__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_37__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._ANC_Door_L_43__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._D_Body_38__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_004__MAT_Polestar_2_Base1_0.geometry} material={bodyMaterial} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_006__MAT_Lights1_0.geometry} material={materials.MAT_Lights1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_007__MAT_Details_MAT1_0.geometry} material={materials.MAT_Details_MAT1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_008__MAT_Details_Chassis_0001_002_0.geometry} material={materials.MAT_Details_Chassis_0001_002} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_RearKit_0000_001_SM_RearKit_0000_MAT_Polestar_2_Base_009__MAT_Carpaint_Black1_0.geometry} material={materials.MAT_Carpaint_Black1} position={[0, 0.2, 0]} />
        <mesh geometry={nodes._SM_Disk_L_0000_001_SM_Disk_L_0000_MAT_Tire_Disk1__MAT_Tire_Disk1_0.geometry} material={materials.MAT_Tire_Disk1} position={[0.789, 0.401, -1.319]} scale={1.112} />
        <mesh geometry={nodes._SM_Disk_R_0000_001_SM_Disk_R_0000_MAT_Tire_Disk_002__MAT_Tire_Disk1_0.geometry} material={materials.MAT_Tire_Disk1} position={[-0.789, 0.401, -1.319]} scale={1.112} />
        <mesh geometry={nodes._SM_Hub_R_0000_001_SM_Hub_R_0000_MAT_Tire_Hub_002__MAT_Tire_Hub1_0.geometry} material={materials.MAT_Tire_Hub1} position={[-0.789, 0.401, -1.319]} scale={[0.676, 1.112, 1.112]} />
        <mesh geometry={nodes._SM_Hub_L_0000_001_SM_Hub_L_0000_MAT_Tire_Hub1__MAT_Tire_Hub1_0.geometry} material={materials.MAT_Tire_Hub1} position={[0.789, 0.401, -1.319]} scale={[0.676, 1.112, 1.112]} />
      </group>
    </group>
  )
}

useGLTF.preload('/2020_polestar.glb')
